CREATE TABLE POST (
	POST_ID BIGINT NOT NULL AUTO_INCREMENT,
	UUID VARCHAR(64) NOT NULL,
	SLUG VARCHAR(250) NOT NULL,
	TITLE VARCHAR(500) NOT NULL,
	CONTENT TEXT NULL,
	PUBLISHED_DATE DATETIME NULL,
	VISIBLE BIT NOT NULL DEFAULT 0,
	ACTIVE BIT NOT NULL DEFAULT 0,
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT PK_POST PRIMARY KEY (POST_ID),
	CONSTRAINT UK_POST_UUID UNIQUE (UUID)
);
